version: '3.9'

services:
  web:
    container_name: 'kavaleridze-ui'
    build:
      context: .
      args:
        - SERVER_URL=http://127.0.0.1:8081/api
    environment:
      NODE_ENV: 'production'
    ports:
      - '8080:80'
    depends_on:
      - api
    restart: on-failure
